version: "3.5"

services:
    auth:
        image: ghcr.io/byeol-i/firebase-auth-module:latest
        hostname: sia.auth
        networks:
            - sia-network
        ports:
            - 50024:50024
        secrets:
            - firebase-key
        # command: "/opt/bin/app/main -local=True"
        command: "/opt/bin/app/main -firebaseProjectID=send-it-anywhere -authAddr=0.0.0.0:50024"
        environment:
            - TZ=Asia/Seoul
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints: [node.role==worker]

networks:
    sia-network:
        external: true

secrets:
    firebase-key:
        file: ./firebase/key.json
    # firebase-key:
    #     external: true
